### ISSUE TITLE
字符串的引号只考虑英文引号，没考虑到中文引号。

### ISSUE THREAD

**Issue by pigpig922** [Hongchenglong/Software-Engineering#1]
**Is your feature request related to a problem? Please describe.**
你的功能要求与问题有关吗？ 请描述。

**Describe the solution you'd like**
描述你想要的解决方案。

**Describe alternatives you've considered**
描述你考虑过的替代方案

**Additional context**
其他内容

**Comment by Hongchenglong** [comment]
明白。改！

**Comment by TieJiang13** [comment]
太完美了我实在是在鸡蛋里挑骨头
有一点可能要改进一下，就是如果出现没有定义的变量 需要提示“无此变量”或者其他提示。
不然没有任何输出，会觉得卡了
![image](https://user-images.githubusercontent.com/52875154/74153153-e87cb800-4c4a-11ea-8dbf-68b3c36e5ea7.png)
![image](https://user-images.githubusercontent.com/52875154/74153066-ad7a8480-4c4a-11ea-8b62-d220a3246b95.png)

太杠了，都不好意思写

**Comment by TieJiang13** [comment]
> 太完美了我实在是在鸡蛋里挑骨头
> 有一点可能要改进一下，就是如果出现没有定义的变量需要提示“无此变量”或者其他提示。
> 不然没有任何输出，会觉得卡了
> ![图片](https://user-images.githubusercontent.com/52875154/74153153-e87cb800-4c4a-11ea-8dbf-68b3c36e5ea7.png)
> ![图片](https://user-images.githubusercontent.com/52875154/74153066-ad7a8480-4c4a-11ea-8b62-d220a3246b95.png)
> 
> 太杠了，都不好意思写

图片能看的见吗

**Comment by Hongchenglong** [comment]
采纳并已解决！
