### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by TieJiang13** [Hongchenglong/Software-Engineering#2]
**Is your feature request related to a problem? Please describe.**
你的功能要求与问题有关吗？ 请描述。
如果出现无关变量，需要给点提示
**Describe the solution you'd like**
描述你想要的解决方案。
在判断“如果”，“看看”，"整数"的同一级添加一条如果以上的三种情况都没出现，反而出现了不存在的变量名，既不是“增加”，也不是“减少”。则可以输出"无此变量"
**Describe alternatives you've considered**
描述你考虑过的替代方案
上面那种方法还没实施，不知道能不能行得通，也没想过其他方案，或者问题。这段程序已经很完美了我实在是在鸡蛋里挑骨头，都不好意思写
**Additional context**
其他内容
实现前和实现后的效果图
![image](https://user-images.githubusercontent.com/52875154/74153153-e87cb800-4c4a-11ea-8dbf-68b3c36e5ea7.png)
![image](https://user-images.githubusercontent.com/52875154/74153066-ad7a8480-4c4a-11ea-8b62-d220a3246b95.png)

**Comment by Hongchenglong** [comment]
谢谢！采纳并已解决！
